comment:
  layout: "header, diff, files"
  hide_project_coverage: false

coverage:
  status:
    project: off
    patch: off

ignore:
  - "test/**"
  - "include/ex_actor/3rd_lib/**"
  - "src/ex_actor/3rd_lib/**"
