github_checks:
  annotations: true

coverage:
  status:
    project:
      default:
        target: auto
        informational: true
    patch:
      default:
        target: auto
        informational: true

ignore:
  - "test/**"
  - "include/ex_actor/3rd_lib/**"
