github_checks:
  annotations: true

comment:
  layout: "reach, diff, files"
  require_changes: true

coverage:
  status:
    project:
      default:
        target: 80
        informational: true
    patch:
      default:
        target: 80
        informational: true

ignore:
  - "test/**"
  - "include/ex_actor/3rd_lib/**"
  - "src/ex_actor/3rd_lib/**"
