site_name: "ex_actor"
site_description: "A modern C++ actor framework based on std::execution"
site_author: "Lixin Wei"
docs_dir: contents
site_url: https://ex-actor.github.io/ex-actor/
repo_name: ex-actor/ex-actor
edit_uri: edit/main/docs/contents
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.path
    - navigation.sections
    - navigation.expand
    - navigation.footer
    - navigation.top
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.action.edit
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ex-actor/ex-actor

repo_url: https://github.com/ex-actor/ex-actor

plugins:
  - search
  - social
  - d2:
      executable: d2 # path to d2 executable
      cache: True
      layout: elk
      theme: 301
      pad: 100
  # - add-number:
  #     order: 2
  # - enumerate-headings:
  #     toc_depth: 6
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: ex-actor/ex-actor
      branch: main

markdown_extensions:
  - toc:
      toc_depth: 3
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Tutorial: tutorial.md
  - Distributed Mode: distributed_mode.md
  - Schedulers: schedulers.md
  - Contributing: contributing.md
