name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      pull-requests: write
      contents: read

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup buildifier
        uses: jbajic/setup-buildifier@v1
        with:
          buildifier-version: 8.2.1

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          version: v0.11.0

      - name: Generate compile_commands.json
        run: |
          ./scripts/regen_build_dir.sh

      - uses: cpp-linter/cpp-linter-action@v2.16.5
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: "file" # Use .clang-format config file
          tidy-checks: "" # Use .clang-tidy config file
          version: "20"
          ignore: "test/import_test|include/ex_actor/3rd_lib"
          ignore-tidy: "**/*.h"
          step-summary: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
